### ISSUE TITLE
Unable to download package

### ISSUE THREAD

**Issue by buraksirma** [brycedorn/deno-steam-openid#1]
Hello, I added the package to Deno project when I tried to start the project but I'm getting the following output. I checked the URL to see if it was wrong but it looked fine.
```
error: Module not found "https://deno.land/x/deno-steam-openid@0.0.1/mod.ts".
    at filepath:1:27
```

**Comment by buraksirma** [comment]
The url was with `-` instead of `_` in Deno land. It worked after I changed the char.

**Comment by brycedorn** [comment]
Yep sorry for the confusion, deno.land only allows [underscores](https://deno.land/add_module) in module names:

> The module name must be between 3 and 40 characters and contain only the characters a-z, 0-9 and _.
